In [1]:
22/7

3.142857142857143

In [10]:
import os
dir(os)

['DirEntry',
 'F_OK',
 'MutableMapping',
 'O_APPEND',
 'O_BINARY',
 'O_CREAT',
 'O_EXCL',
 'O_NOINHERIT',
 'O_RANDOM',
 'O_RDONLY',
 'O_RDWR',
 'O_SEQUENTIAL',
 'O_SHORT_LIVED',
 'O_TEMPORARY',
 'O_TEXT',
 'O_TRUNC',
 'O_WRONLY',
 'P_DETACH',
 'P_NOWAIT',
 'P_NOWAITO',
 'P_OVERLAY',
 'P_WAIT',
 'PathLike',
 'R_OK',
 'SEEK_CUR',
 'SEEK_END',
 'SEEK_SET',
 'TMP_MAX',
 'W_OK',
 'X_OK',
 '_AddedDllDirectory',
 '_Environ',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_check_methods',
 '_execvpe',
 '_exists',
 '_exit',
 '_fspath',
 '_get_exports_list',
 '_putenv',
 '_unsetenv',
 '_wrap_close',
 'abc',
 'abort',
 'access',
 'add_dll_directory',
 'altsep',
 'chdir',
 'chmod',
 'close',
 'closerange',
 'cpu_count',
 'curdir',
 'defpath',
 'device_encoding',
 'devnull',
 'dup',
 'dup2',
 'environ',
 'error',
 'execl',
 'execle',
 'execlp',
 'execlpe',
 'execv',
 'execve',
 'execvp',
 'execvpe',
 'extsep',
 'fdopen

In [17]:
os.listdir()

['.anaconda',
 '.android',
 '.AndroidStudio4.0',
 '.astropy',
 '.cache',
 '.conda',
 '.condarc',
 '.config',
 '.gitconfig',
 '.gradle',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.matplotlib',
 '.packettracer',
 '.python_history',
 '.spyder-py3',
 '.VirtualBox',
 '.vscode',
 '3D Objects',
 'AndroidStudioProjects',
 'AppData',
 'Application Data',
 'Cisco Packet Tracer 5.3.3',
 'Contacts',
 'Cookies',
 'debug.log',
 'Documents',
 'Downloads',
 'Elite_Internship.ipynb',
 'Favorites',
 'FDSassignment.ipynb',
 'input.txt',
 'IntelGraphicsProfiles',
 'Links',
 'Local Settings',
 'MicrosoftEdgeBackups',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{8224373e-8fba-11eb-a60c-6c2b594c780a}.TM.blf',
 'NTUSER.DAT{8224373e-8fba-11eb-a60c-6c2b594c780a}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{8224373e-8fba-11eb-a60c-6c2b594c780a}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'Oracle',


In [15]:
!DIR

 Volume in drive C is OS
 Volume Serial Number is E2E4-C703

 Directory of C:\Users\dell

06-09-2021  02:07    <DIR>          .
06-09-2021  02:07    <DIR>          ..
06-09-2021  01:55    <DIR>          .anaconda
19-07-2020  01:12    <DIR>          .android
17-07-2020  00:35    <DIR>          .AndroidStudio4.0
06-09-2021  01:54    <DIR>          .astropy
25-05-2021  01:45    <DIR>          .cache
06-09-2021  02:07    <DIR>          .conda
06-09-2021  01:51                43 .condarc
06-09-2021  01:54    <DIR>          .config
30-08-2021  20:47                62 .gitconfig
17-07-2020  00:57    <DIR>          .gradle
20-08-2021  19:36    <DIR>          .ipynb_checkpoints
09-08-2020  01:18    <DIR>          .ipython
09-08-2020  01:29    <DIR>          .jupyter
09-08-2020  01:18    <DIR>          .matplotlib
25-08-2021  17:18               186 .packettracer
31-10-2020  18:27               274 .python_history
30-08-2020  17:59    <DIR>          .spyder-py3
25-05-2021  01:36    <DIR>        

In [21]:
import numpy as np


In [22]:
numpy

<module 'numpy' from 'D:\\Users\\dell\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [27]:
lst = [[1,2,3,9],[4,5,6,9],[7,8,9,9]]
lst

[[1, 2, 3, 9], [4, 5, 6, 9], [7, 8, 9, 9]]

In [28]:
type(lst)

list

In [29]:
np_array = np.array(lst)

In [30]:
np_array

array([[1, 2, 3, 9],
       [4, 5, 6, 9],
       [7, 8, 9, 9]])

In [33]:
np.shape(np_array)

(3, 4)

In [36]:
np_array = np.reshape(np_array,(4,3))

In [37]:
np_array

array([[1, 2, 3],
       [9, 4, 5],
       [6, 9, 7],
       [8, 9, 9]])

In [38]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [39]:
np.linspace(10,30,20)

array([10.        , 11.05263158, 12.10526316, 13.15789474, 14.21052632,
       15.26315789, 16.31578947, 17.36842105, 18.42105263, 19.47368421,
       20.52631579, 21.57894737, 22.63157895, 23.68421053, 24.73684211,
       25.78947368, 26.84210526, 27.89473684, 28.94736842, 30.        ])

In [41]:
import pandas as pd